### ISSUE TITLE
ValueError: Gas estimation failed

### ISSUE THREAD

**Issue by dennislblog** [smartcontractkit/chainlink-mix#21]
Hi, I am a new user of `brownie`. I keep getting this error when I'm running `chainlink_api_scripts/02_request_api.py`. I wonder what could go wrong. Thank you for your explanation. 

```bash
ValueError: Gas estimation failed: 'execution reverted'. This transaction will likely revert. If you wish to broadcast, you must set the gas limit manually.
```

**Comment by pappas999** [comment]
hi @dennislblog , does the wallet linked to your account used to deploy/interact with contracts have at least 1 LINK in it, and also some ETH?

**Comment by dennislblog** [comment]
Thank you for your explanation. It works indeed after I add some coins to my account.
