### ISSUE TITLE
Cannot find scripts/price_feed_scripts/deploy_price_consumer_v3.py

### ISSUE THREAD

**Issue by sabin88** [smartcontractkit/chainlink-mix#31]
I am doing Patrick's tutorial from [here](https://dev.to/patrickalphac/using-brownie-for-to-deploy-smart-contracts-1kkp), after calling `brownie run scripts/price_feed_scripts/deploy_price_consumer_v3.py --network kovan` I get the following error:

```
ChainlinkProject is the active project.
  File "c:\users\szabi\appdata\roaming\python\python38\lib\site-packages\brownie\_cli\__main__.py", line 64, in main
    importlib.import_module(f"brownie._cli.{cmd}").main()
  File "c:\users\szabi\appdata\roaming\python\python38\lib\site-packages\brownie\_cli\run.py", line 46, in main
    path, _ = _get_path(args["<filename>"])
  File "c:\users\szabi\appdata\roaming\python\python38\lib\site-packages\brownie\project\scripts.py", line 130, in _get_path
    raise FileNotFoundError(f"Cannot find {path_str}")
FileNotFoundError: Cannot find scripts/price_feed_scripts/deploy_price_consumer_v3.py
```

I assume the filenames were updated and brownie bakes an old version because I have `01_deploy_price_consumer_v3.py
` and it requires `deploy_price_consumer_v3.py`

**Comment by PatrickAlphaC** [comment]
You're right, please use `01_deploy_price_consumer_v3.py`

Could you please follow the readme of this repo? I've updated the blog. Let me know if it still doesn't work? Thanks!
