### ISSUE TITLE
```suggestion

### ISSUE THREAD

**Issue by JMP2590** [smartcontractkit/chainlink-mix#45]
```suggestion
      .connect(0xd662F96359b34Fb3430e81Bb0a1b6C0B49F36CE6)
```

__Originally posted by @JMP2590 in https://github.com/JMP2590/chainlink/pull/39#discussion_r876585288__

**Comment by pappas999** [comment]
hi, can you please provide more info on this @JMP2590 , I can't make sense of the issue raised
