### ISSUE TITLE
Add ENS to the chainlink-mix

### ISSUE THREAD

**Issue by PatrickAlphaC** [smartcontractkit/chainlink-mix#5]
A handy trick with 
@BrownieEth
 and 
@Chainlink

def price(pair):
    return Contract(f'{pair}.data.eth').latestAnswer() / 1e8

>>> price('yfi-usd')
34937.30811431

**Comment by chainlink** [comment]
Can you please stop tagging me in this repo?

**Comment by PatrickAlphaC** [comment]
Ah sorry, will do.

**Comment by PatrickAlphaC** [comment]
addressed in https://github.com/smartcontractkit/chainlink-mix/pull/8
