### ISSUE TITLE
brownie test is stuck

### ISSUE THREAD

**Issue by Sk-Azraf-Sami** [smartcontractkit/chainlink-mix#58]
I just run these command: 
`brownie bake chainlink-mix`,  `cd chainlink` and `brownie test`
Now test is stuck at this point: _tests/test_api_consumer.py_ ......

**Comment by zeuslawyer** [comment]
Hi @Sk-Azraf-Sami 
Brownie is deprecated / no longer maintained (https://github.com/eth-brownie/brownie?tab=readme-ov-file#brownie)
I recommend you look for the other starter kits here
https://github.com/smartcontractkit/starter-kits

Foundry and Hardhat are the most commonly used tools for blockchain dev and you'll have excellent support for those.
